### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by snikeguo** [maekawatoshiki/yacht#2]
cargo test
   Compiling memchr v2.4.1
   Compiling libc v0.2.112
   Compiling lazy_static v1.4.0
   Compiling regex v0.2.11
   Compiling ucd-util v0.1.8
   Compiling utf8-ranges v1.0.4
   Compiling semver-parser v0.7.0
   Compiling cc v1.0.72
   Compiling unicode-width v0.1.9
   Compiling ansi_term v0.12.1
   Compiling vec_map v0.8.2
   Compiling strsim v0.8.0
   Compiling bitflags v1.3.2
   Compiling rustc-hash v1.1.0
   Compiling ansi_term v0.9.0
   Compiling id-arena v2.2.1
   Compiling thread_local v0.3.6
   Compiling textwrap v0.11.0
   Compiling regex-syntax v0.5.6
   Compiling semver v0.9.0
   Compiling aho-corasick v0.6.10
   Compiling atty v0.2.14
   Compiling clap v2.34.0
   Compiling llvm-sys v60.6.0
error: failed to run custom build command for `llvm-sys v60.6.0`

Caused by:
  process didn't exit successfully: `/root/yacht/target/debug/build/llvm-sys-39261f48e0211d72/build-script-build` (exit status: 101)
  --- stdout
  Didn't find usable system-wide LLVM.
  No suitable version of LLVM was found system-wide or pointed
                    to by LLVM_SYS_60_PREFIX.

                    Consider using `llvmenv` to compile an appropriate copy of LLVM, and
                    refer to the llvm-sys documentation for more information.

                    llvm-sys: https://crates.io/crates/llvm-sys
                    llvmenv: https://crates.io/crates/llvmenv

  --- stderr
  thread 'main' panicked at 'Could not find a compatible version of LLVM', /root/.cargo/registry/src/mirrors.ustc.edu.cn-12df342d903acd47/llvm-sys-60.6.0/build.rs:63:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
root@SC-202008062128:~/yacht# cargo test
   Compiling llvm-sys v60.6.0
error: failed to run custom build command for `llvm-sys v60.6.0`

Caused by:
  process didn't exit successfully: `/root/yacht/target/debug/build/llvm-sys-39261f48e0211d72/build-script-build` (exit status: 101)
  --- stdout
  Didn't find usable system-wide LLVM.
  No suitable version of LLVM was found system-wide or pointed
                    to by LLVM_SYS_60_PREFIX.

                    Consider using `llvmenv` to compile an appropriate copy of LLVM, and
                    refer to the llvm-sys documentation for more information.

                    llvm-sys: https://crates.io/crates/llvm-sys
                    llvmenv: https://crates.io/crates/llvmenv

  --- stderr
  thread 'main' panicked at 'Could not find a compatible version of LLVM', /root/.cargo/registry/src/mirrors.ustc.edu.cn-12df342d903acd47/llvm-sys-60.6.0/build.rs:63:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
root@SC-202008062128:~/yacht# cargo test
    Updating `ustc` index
   Compiling llvm-sys v60.6.0
error: failed to run custom build command for `llvm-sys v60.6.0`

Caused by:
  process didn't exit successfully: `/root/yacht/target/debug/build/llvm-sys-39261f48e0211d72/build-script-build` (exit status: 101)
  --- stdout
  Didn't find usable system-wide LLVM.
  No suitable version of LLVM was found system-wide or pointed
                    to by LLVM_SYS_60_PREFIX.

                    Consider using `llvmenv` to compile an appropriate copy of LLVM, and
                    refer to the llvm-sys documentation for more information.

                    llvm-sys: https://crates.io/crates/llvm-sys
                    llvmenv: https://crates.io/crates/llvmenv

  --- stderr
  thread 'main' panicked at 'Could not find a compatible version of LLVM', /root/.cargo/registry/src/mirrors.ustc.edu.cn-12df342d903acd47/llvm-sys-60.6.0/build.rs:63:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

--------------------------------
# rustc --version
# rustc 1.59.0-nightly (cfa4ac66c 2022-01-06)

**Comment by maekawatoshiki** [comment]
Do you have llvm 6.0 installed?

**Comment by snikeguo** [comment]
> 是否安装了 llvm 6.0？

YES

**Comment by snikeguo** [comment]
~/yacht# apt-get install llvm-6.0 libgc-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
libgc-dev is already the newest version (1:7.6.4-0.4ubuntu1).
llvm-6.0 is already the newest version (1:6.0.1-14).
0 upgraded, 0 newly installed, 0 to remove and 259 not upgraded.

**Comment by maekawatoshiki** [comment]
`export LLVM_SYS_60_PREFIX=$(llvmenv prefix)` may work.

**Comment by snikeguo** [comment]
ln -sf /usr/bin/llvm-config-6.0 /usr/bin/llvm-config

> export LLVM_SYS_60_PREFIX=$(llvmenv prefix)

 ln -sf /usr/bin/llvm-config-6.0 /usr/bin/llvm-config

**Comment by snikeguo** [comment]
as the type system is concerned
     = help: for more information, see https://doc.rust-lang.org/reference/destructors.html

warning: getting the inner pointer of a temporary `CString`
    --> src/exec/jit/jit.rs:1709:82
     |
1709 |                 LLVMModuleCreateWithNameInContext(CString::new("yacht").unwrap().as_ptr(), context);
     |                                                   ------------------------------ ^^^^^^ this pointer will be invalid
     |                                                   |
     |                                                   this `CString` is deallocated at the end of the statement, bind it to a variable to extend its lifetime
     |
     = note: pointers do not have a lifetime; when calling `as_ptr` the `CString` will be deallocated at the end of the statement because nothing is referencing it as far as the type system is concerned
     = help: for more information, see https://doc.rust-lang.org/reference/destructors.html

   Compiling yacht v0.1.0 (/root/yacht)
warning: `yacht` (lib) generated 20 warnings
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-m64" "/root/yacht/target/debug/deps/yacht-85f01c7af7c16e0f.1dzcll9xzy4e4vsy.rcgu.o" "/root/yacht/target/debug/deps/yacht-85f01c7af7c16e0f.1upbq658vl4pf9i2.rcgu.o" "/root/yacht/target/debug/deps/yacht-85f01c7af7c16e0f.2qnq09u28thaouny.rcgu.o" "/root/yacht/target/debug/deps/yacht-85f01c7af7c16e0f.2vvhbyuigbcr457g.rcgu.o" "/root/yacht/target/debug/deps/yacht-85f01c7af7c16e0f.2wzm577vrioz1y2n.rcgu.o" "/root/yacht/target/debug/deps/yacht-85f01c7af7c16e0f.3fgj61okfnofdxrq.rcgu.o" "/root/yacht/target/debug/deps/yacht-85f01c7af7c16e0f.3k0i4k057v1zi247.rcgu.o" "/root/yacht/target/debug/deps/yacht-85f01c7af7c16e0f.3kilqzj6cfjuzfj2.rcgu.o" "/root/yacht/target/debug/deps/yacht-85f01c7af7c16e0f.3ks8fep0mfv054wu.rcgu.o" "/root/yacht/target/debug/deps/yacht-85f01c7af7c16e0f.3kv3k952hh9ixfv7.rcgu.o" "/root/yacht/target/debug/deps/yacht-85f01c7af7c16e0f.4cly34qiysl6gsi8.rcgu.o" "/root/yacht/target/debug/deps/yacht-85f01c7af7c16e0f.4hvi689q7frx7r89.rcgu.o" "/root/yacht/target/debug/deps/yacht-85f01c7af7c16e0f.56wir1c0s60lgqdw.rcgu.o" "/root/yacht/target/debug/deps/yacht-85f01c7af7c16e0f.593zcwfy97wr0pjf.rcgu.o" "/root/yacht/target/debug/deps/yacht-85f01c7af7c16e0f.5dtgf3dve72zodtw.rcgu.o" "/root/yacht/target/debug/deps/yacht-85f01c7af7c16e0f.r63wyi10gq05enx.rcgu.o" "/root/yacht/target/debug/deps/yacht-85f01c7af7c16e0f.5y8rtk3f6zqqe3y.rcgu.o" "-Wl,--as-needed" "-L" "/root/yacht/target/debug/deps" "-L" "/root/yacht/target/debug/build/llvm-sys-bd0efdf9bb1cc27a/out" "-L" "/usr/lib/llvm-6.0/lib" "-L" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-lgc" "-Wl,-Bstatic" "/root/yacht/target/debug/deps/libansi_term-61ff796a2ea4f2af.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libtest-39a7739a1809dcca.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgetopts-70ef5500cb077bd5.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunicode_width-c5b638efcfd38001.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_std-639c108057d47320.rlib" "/root/yacht/target/debug/deps/librustc_hash-8453996512cfe219.rlib" "/root/yacht/target/debug/deps/libllvm_sys-1bf0c6dc05989857.rlib" "/root/yacht/target/debug/deps/liblibc-b1fd85efdbe244b8.rlib" "/root/yacht/target/debug/deps/libid_arena-ce777a68a9fb9505.rlib" "-Wl,--start-group" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-c46e4336da0ba77b.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-9cb5ef8235cf10de.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-c94e3d0069d19330.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-5a532766d1e80b5b.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-d08f0c83526179dc.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libmemchr-d995c6cafdb3d253.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-02ebc04a72bd9433.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-5cbc32ae14534ca9.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_detect-969ebc8623abfcc9.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-7f98f837d3579544.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-b96a8aea2dd7bf12.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-c7b2792f3bc0d0eb.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-7558dde8464d46ce.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-b3d84848ab790cf7.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-f48e57d6d73020ee.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-ffaac76756e3f83b.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-2a6a2797f7a73818.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-0e3656b1fda5fd7b.rlib" "-Wl,--end-group" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-f98cce041f593917.rlib" "-Wl,-Bdynamic" "-lz" "-lrt" "-ldl" "-ltinfo" "-lpthread" "-lm" "-lstdc++" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/root/yacht/target/debug/deps/yacht-85f01c7af7c16e0f" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro,-znow" "-nodefaultlibs"
  = note: /usr/bin/ld: cannot find -lz
          collect2: error: ld returned 1 exit status


warning: `yacht` (lib test) generated 20 warnings (20 duplicates)
error: could not compile `yacht` due to previous error; 20 warnings emitted
warning: build failed, waiting for other jobs to finish...
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-m64" "/root/yacht/target/debug/deps/yacht-5e3af6add98f55ed.18df50ghn0kdkrxb.rcgu.o" "/root/yacht/target/debug/deps/yacht-5e3af6add98f55ed.1kqoplxzqvi2irq5.rcgu.o" "/root/yacht/target/debug/deps/yacht-5e3af6add98f55ed.1xamjxa6ln5gew05.rcgu.o" "/root/yacht/target/debug/deps/yacht-5e3af6add98f55ed.2dclexv609kpdqtt.rcgu.o" "/root/yacht/target/debug/deps/yacht-5e3af6add98f55ed.33dfwe6sly98weac.rcgu.o" "/root/yacht/target/debug/deps/yacht-5e3af6add98f55ed.3bj7v7e5kprcux4u.rcgu.o" "/root/yacht/target/debug/deps/yacht-5e3af6add98f55ed.3rqwhp18etyyee3t.rcgu.o" "/root/yacht/target/debug/deps/yacht-5e3af6add98f55ed.4xnuchf5k62rtwss.rcgu.o" "/root/yacht/target/debug/deps/yacht-5e3af6add98f55ed.56va31bfm38t97dl.rcgu.o" "/root/yacht/target/debug/deps/yacht-5e3af6add98f55ed.87soyxuw8ei08oo.rcgu.o" "/root/yacht/target/debug/deps/yacht-5e3af6add98f55ed.aldm6e6nga9h2md.rcgu.o" "/root/yacht/target/debug/deps/yacht-5e3af6add98f55ed.izszjiw2fm7if9m.rcgu.o" "/root/yacht/target/debug/deps/yacht-5e3af6add98f55ed.o1t41631aq6juvg.rcgu.o" "/root/yacht/target/debug/deps/yacht-5e3af6add98f55ed.r1nn4d2v2nrm0bc.rcgu.o" "/root/yacht/target/debug/deps/yacht-5e3af6add98f55ed.snazl1zw6cl977k.rcgu.o" "/root/yacht/target/debug/deps/yacht-5e3af6add98f55ed.tothnfw8q6gvmk.rcgu.o" "/root/yacht/target/debug/deps/yacht-5e3af6add98f55ed.1op2kgk09gicduqf.rcgu.o" "-Wl,--as-needed" "-L" "/root/yacht/target/debug/deps" "-L" "/root/yacht/target/debug/build/llvm-sys-bd0efdf9bb1cc27a/out" "-L" "/usr/lib/llvm-6.0/lib" "-L" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libtest-39a7739a1809dcca.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgetopts-70ef5500cb077bd5.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunicode_width-c5b638efcfd38001.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_std-639c108057d47320.rlib" "/root/yacht/target/debug/deps/libclap-cb10f802f59b6e79.rlib" "/root/yacht/target/debug/deps/libvec_map-cf0b7e37153361b1.rlib" "/root/yacht/target/debug/deps/libtextwrap-5a5d2d9c7b13a75a.rlib" "/root/yacht/target/debug/deps/libunicode_width-8b54014aa45bb529.rlib" "/root/yacht/target/debug/deps/libstrsim-cca90d4895c4fd62.rlib" "/root/yacht/target/debug/deps/libbitflags-7713d60f4d3eae70.rlib" "/root/yacht/target/debug/deps/libatty-15cecff860f40dd1.rlib" "/root/yacht/target/debug/deps/libansi_term-daf68778d04274da.rlib" "/root/yacht/target/debug/deps/libyacht-9771ad6931cef640.rlib" "/root/yacht/target/debug/deps/libansi_term-61ff796a2ea4f2af.rlib" "/root/yacht/target/debug/deps/librustc_hash-8453996512cfe219.rlib" "/root/yacht/target/debug/deps/libllvm_sys-1bf0c6dc05989857.rlib" "/root/yacht/target/debug/deps/liblibc-b1fd85efdbe244b8.rlib" "/root/yacht/target/debug/deps/libid_arena-ce777a68a9fb9505.rlib" "-Wl,--start-group" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-c46e4336da0ba77b.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-9cb5ef8235cf10de.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-c94e3d0069d19330.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-5a532766d1e80b5b.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-d08f0c83526179dc.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libmemchr-d995c6cafdb3d253.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-02ebc04a72bd9433.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-5cbc32ae14534ca9.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_detect-969ebc8623abfcc9.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-7f98f837d3579544.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-b96a8aea2dd7bf12.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-c7b2792f3bc0d0eb.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-7558dde8464d46ce.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-b3d84848ab790cf7.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-f48e57d6d73020ee.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-ffaac76756e3f83b.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-2a6a2797f7a73818.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-0e3656b1fda5fd7b.rlib" "-Wl,--end-group" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-f98cce041f593917.rlib" "-Wl,-Bdynamic" "-lgc" "-lz" "-lrt" "-ldl" "-ltinfo" "-lpthread" "-lm" "-lstdc++" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/root/yacht/target/debug/deps/yacht-5e3af6add98f55ed" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro,-znow" "-nodefaultlibs"
  = note: /usr/bin/ld: cannot find -lz
          collect2: error: ld returned 1 exit status


error: build failed

**Comment by maekawatoshiki** [comment]
`apt-get install zlib1g-dev` ?

**Comment by snikeguo** [comment]
> `apt-get install zlib1g-dev` ?

YES!!! test OK , thank you! good night~~
